databases:
  - name: raffle-db
    plan: free
    databaseName: raffle_db
    user: duke

services:
  - type: web
    plan: free
    name: raffle-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn raffle.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: raffle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALGORITHM
        value: "HS256"
      - key: USER_ID_FIELD
        value: "id"
      - key: USER_ID_CLAIM
        value: "user_id"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"