databases:
  - name: raffle-db
    plan: free
    databaseName: raffle-db  # Changed to match your local database name
    user: postgres              # Changed to match your local PostgreSQL username

services:
  - type: web
    plan: free
    name: raffle-api           # Changed to reflect your project name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn raffle.asgi:application -k uvicorn.workers.UvicornWorker"  # Updated to match your project structure
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: raffle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
