# Generated by Django 5.1.1 on 2024-09-12 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='raffles', to=settings.AUTH_USER_MODEL),
        ),
    ]
