# Generated by Django 5.1.1 on 2024-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_raffle_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='prize_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='prize_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
