# Generated by Django 5.1.1 on 2024-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_raffle_prize_img_raffle_prize_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='prize_img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='prize_name',
            field=models.CharField(max_length=255),
        ),
    ]
