# Generated by Django 5.1.1 on 2024-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='momo_transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='momo_transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='flutterwave', max_length=50),
        ),
    ]
