# Generated by Django 5.1.1 on 2024-10-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_stripe_payment_intent_id_payment_momo_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='momo_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='momo_transaction_status',
        ),
    ]
