# Generated by Django 5.1.1 on 2024-10-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_flutterwave_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
