# Generated by Django 5.1.1 on 2024-10-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=659808331, max_length=20),
            preserve_default=False,
        ),
    ]
