# Generated by Django 5.1.1 on 2024-09-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_raffle_participants'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle'),
        ),
    ]
