# Generated by Django 5.1.1 on 2024-09-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketHolders', '0002_ticketholders_delete_ticketusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_won', models.DateTimeField(auto_now_add=True)),
                ('ticket_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ticketHolders.ticketholders')),
            ],
        ),
    ]
